### ISSUE TITLE
Google Cloud Platform Compatibility

### ISSUE THREAD

**Issue by jkylearmstrong** [dermatologist/pyomop#9]
Wondering if you have tested with OMOP on GCP:
https://console.cloud.google.com/marketplace/product/odysseusinc-public/ohdsi-atlas?q=atlas&id=959d1815-500f-41ea-a1a8-cacc5f804764&_ga=2.144994237.-866717448.1626880492

**Comment by dermatologist** [comment]
Hi @jkylearmstrong Nope. I don't have an account. I think, it may be better to use [Whistle on GCP.](https://github.com/GoogleCloudPlatform/healthcare-data-harmonization)
